# Editor completion
"$schema" = 'https://starship.rs/config-schema.json'

# Disable initial new line
add_newline = false

# Appearance
format = """
$time
$directory\
$git_branch
$cmd_duration\
$character
"""

[time]
disabled = false
format = "[$time]($style)"
time_format = '%a %h %-e %-l:%M %p'
use_12hr = true
style = 'bold blue'

[directory]
truncation_length = 0
truncate_to_repo = false
before_repo_root_style = 'dimmed bold cyan'
repo_root_style = 'bold cyan'

# Nerd Font symbol
[git_branch]
symbol = " "

[cmd_duration]
format = "took [$duration]($style)\n"

[character]
success_symbol = '[➜](bold green)'
error_symbol = '[➜](bold red)'

[sudo]
disabled = false
style = 'bold red'
